"use strict";
(self.webpackChunk_twitter_responsive_web = self.webpackChunk_twitter_responsive_web || []).push([
    ["shared~ondemand.SettingsRevamp~ondemand.SettingsMonetization~ondemand.SettingsSuperFollows~ondemand.SettingsA"],
    {
        980407: (a, e, t) => {
            t.d(e, { Z: () => b, w: () => l });
            var i = t(202784),
                n = t(325686),
                p = t(108362),
                r = t(386802),
                A = t(392237),
                g = t(652904),
                o = t(555079),
                d = t(625661),
                h = t(449067),
                s = t(715601);
            class l extends i.Component {
                constructor(...a) {
                    super(...a),
                        (this._renderChildViewAppBar = () => {
                            const { appBarRef: a, appBarStyle: e, backButtonType: t, backLocation: p, centerTitle: r, hideBackButton: A, history: g, isFullWidth: h, isLarge: s, middleControl: l, onBackClick: b, rightControl: f, secondaryBar: x, subtitle: u, title: w } = this.props,
                                { isModal: B } = this.context;
                            return i.createElement(n.Z, { style: B ? [c.childViewAppBarRoot, c.appBarZindex] : c.appBarZindex }, i.createElement(d.ZP, { backButtonType: t || (B ? "close" : "back"), backLocation: p, centerTitle: r, fixed: !B, hideBackButton: A, history: g, isFullWidth: h, isLarge: s, middleControl: l, onBackClick: b, ref: a, rightControl: f, secondaryBar: x, style: [B && c.appBarModal, e], subtitle: u, title: w, titleDomId: o.Q_ }));
                        }),
                        (this._handleLayout = (a) => {
                            const { onLayout: e } = this.props,
                                { isModal: t } = this.context;
                            e && (t ? window.requestAnimationFrame(() => e(a)) : e(a));
                        });
                }
                render() {
                    const { "aria-hidden": a, bottomBar: e, children: t, containerStyle: r, documentTitle: A, isFullWidth: o, isLarge: d, renderHeader: l, title: b, withoutBottomBarMobile: f } = this.props,
                        { isModal: x } = this.context,
                        u = l ? l(this._renderChildViewAppBar()) : this._renderChildViewAppBar();
                    return i.createElement(g.Z, null, i.createElement(h.Z.Configure, { documentTitle: A, headerless: !0, title: b }), i.createElement(n.Z, { "aria-hidden": a, onLayout: this._handleLayout, style: [c.root, x && c.rootModal] }, !x && u, i.createElement(p.Z, { isFullWidth: o, isLarge: d, style: [c.container, x && c.containerModal, r] }, x ? i.createElement(s.Z, { style: c.viewport }, u, t) : t), e ? i.createElement(n.Z, { style: [c.bottomBarModal, !x && !f && c.bottomBarMobile] }, i.createElement(p.Z, { isFullWidth: o, isLarge: d }, e)) : null));
                }
            }
            (l.defaultProps = { isFullWidth: !1, isLarge: !1 }), (l.contextType = r.Z);
            const c = A.default.create((a) => ({ root: { backgroundColor: a.colors.cellBackground, flexGrow: 1, flexShrink: 1 }, rootModal: { borderRadius: a.borderRadii.xLarge, flexShrink: 1 }, appBarModal: { borderTopStartRadius: a.borderRadii.small, borderTopEndRadius: a.borderRadii.small }, childViewAppBarRoot: { position: "sticky", top: 0 }, appBarZindex: { zIndex: a.componentZIndices.appBarZIndex }, container: { flexGrow: 1 }, containerModal: { flexShrink: 1 }, viewport: { borderBottomStartRadius: a.borderRadii.xLarge, borderBottomEndRadius: a.borderRadii.xLarge, flexGrow: 1, flexShrink: 1, overflow: "auto", zIndex: void 0 }, bottomBarModal: { borderTopColor: a.colors.borderColor, borderTopWidth: a.borderWidths.small }, bottomBarMobile: { position: "fixed", backfaceVisibility: "hidden", bottom: 0, width: "100%", paddingBottom: A.default.iPhoneOffsetBottom, backgroundColor: a.colors.navigationBackground, borderTopStyle: "solid" } })),
                b = l;
        },
        698537: (a, e, t) => {
            t.d(e, { j: () => Ce, Z: () => me });
            var i = t(202784),
                n = t(325686),
                p = t(530525),
                r = t(439592),
                A = t(392237);
            const g = t.p + "Arrow.bbf355fa.png",
                o = t.p + "Arrow@2x.1079fd3a.png",
                d = t.p + "Arrow@3x.4bb73bfa.png",
                h = t.p + "Award.68be832a.png",
                s = t.p + "Award@2x.a0c59f8a.png",
                l = t.p + "Award@3x.7a6f947a.png",
                c = t.p + "Badge.22294b2a.png",
                b = t.p + "Badge@2x.c1db7fca.png",
                f = t.p + "Badge@3x.abdf748a.png",
                x = t.p + "Bench.ed6113aa.png",
                u = t.p + "Bench@2x.49eea9ea.png",
                w = t.p + "Bench@3x.eb78fbba.png",
                B = t.p + "Bonus.b7580a8a.png",
                C = t.p + "Bonus@2x.be02885a.png",
                m = t.p + "Bonus@3x.f1da98aa.png",
                v = t.p + "Cat.581a02ca.png",
                T = t.p + "Cat@2x.f2c0bc6a.png",
                S = t.p + "Cat@3x.e8bbed5a.png",
                P = t.p + "Chat.62494e6a.png",
                k = t.p + "Chat@2x.f6eeca0a.png",
                y = t.p + "Chat@3x.dd8438ca.png",
                R = t.p + "Clipboard.279374fa.png",
                E = t.p + "Clipboard@2x.13b4b63a.png",
                L = t.p + "Clipboard@3x.a07957da.png",
                M = t.p + "Cog.788d351a.png",
                z = t.p + "Cog@2x.3528d16a.png",
                U = t.p + "Cog@3x.e4185e9a.png",
                Z = t.p + "Coin.684ea18a.png",
                F = t.p + "Coin@2x.9e02069a.png",
                G = t.p + "Coin@3x.d5ecbc9a.png",
                H = t.p + "CoinPurse.5e7e5f2a.png",
                V = t.p + "CoinPurse@2x.62abfada.png",
                D = t.p + "CoinPurse@3x.6b9f5d0a.png",
                W = t.p + "CoinsHand.f6f5813a.png",
                _ = t.p + "CoinsHand@2x.0da86fba.png",
                O = t.p + "CoinsHand@3x.371d543a.png",
                I = t.p + "CoinsStairs.295fdeaa.png",
                N = t.p + "CoinsStairs@2x.22eb2a2a.png",
                Q = t.p + "CoinsStairs@3x.ea04943a.png",
                J = t.p + "CoinsThumbs.d702e22a.png",
                X = t.p + "CoinsThumbs@2x.b8a2cd1a.png",
                K = t.p + "CoinsThumbs@3x.695f875a.png",
                j = t.p + "Cone.e7e68c9a.png",
                q = t.p + "Cone@2x.94d66a1a.png",
                Y = t.p + "Cone@3x.f471865a.png",
                $ = t.p + "ConfusedDog.f329e38a.png",
                aa = t.p + "ConfusedDog@2x.74c93d1a.png",
                ea = t.p + "ConfusedDog@3x.baf8e90a.png",
                ta = t.p + "Cross.eed0ff5a.png",
                ia = t.p + "Cross@2x.6824943a.png",
                na = t.p + "Cross@3x.5959505a.png",
                pa = t.p + "Crown.65bc0d5a.png",
                ra = t.p + "DiscoGlobe.ed123c4a.png",
                Aa = t.p + "DiscoGlobe@2x.525325ea.png",
                ga = t.p + "DiscoGlobe@3x.490e4c6a.png",
                oa = t.p + "FirstAid.962ae7ea.png",
                da = t.p + "FirstAid@2x.0964005a.png",
                ha = t.p + "FirstAid@3x.b6884b1a.png",
                sa = t.p + "Gem.6a25e93a.png",
                la = t.p + "Gem@2x.9fdab1ea.png",
                ca = t.p + "Gem@3x.9f51f0ca.png",
                ba = t.p + "Heart.a7bdca8a.png",
                fa = t.p + "Heart@2x.a3108cea.png",
                xa = t.p + "Heart@3x.2866f2fa.png",
                ua = t.p + "LifeSaver.19af1fba.png",
                wa = t.p + "LifeSaver@2x.5f9465aa.png",
                Ba = t.p + "LifeSaver@3x.3cde1caa.png",
                Ca = t.p + "Lightbulb.632a0dea.png",
                ma = t.p + "Lightbulb@2x.ea0a7dca.png",
                va = t.p + "Lightbulb@3x.d47fac7a.png",
                Ta = t.p + "NoEntry.89a117aa.png",
                Sa = t.p + "NoEntry@2x.6460d27a.png",
                Pa = t.p + "NoEntry@3x.cf8e946a.png",
                ka = t.p + "OneFinger.2700aaaa.png",
                ya = t.p + "OneFinger@2x.d52597aa.png",
                Ra = t.p + "OneFinger@3x.ff8ba62a.png",
                Ea = t.p + "PaperAirplane.89b2359a.png",
                La = t.p + "PaperAirplane@2x.9fec7eda.png",
                Ma = t.p + "PaperAirplane@3x.7a3f9cfa.png",
                za = t.p + "Pencil.6ac7a9aa.png",
                Ua = t.p + "Pencil@2x.e6d394ca.png",
                Za = t.p + "Pencil@3x.7e45c2ea.png",
                Fa = t.p + "PiggyBank.571af82a.png",
                Ga = t.p + "PiggyBank@2x.f6b3cb1a.png",
                Ha = t.p + "PiggyBank@3x.f166bc1a.png",
                Va = t.p + "Plant.2e93bbba.png",
                Da = t.p + "Plant@2x.5660c14a.png",
                Wa = t.p + "Plant@3x.60b6685a.png",
                _a = t.p + "Puzzle.5148ca8a.png",
                Oa = t.p + "Puzzle@2x.33f30e6a.png",
                Ia = t.p + "Puzzle@3x.3231b3aa.png",
                Na = t.p + "PuzzlePieces.5917591a.png",
                Qa = t.p + "PuzzlePieces@2x.d239439a.png",
                Ja = t.p + "PuzzlePieces@3x.ed9bd73a.png",
                Xa = t.p + "Ribbon.a0d66a6a.png",
                Ka = t.p + "Ribbon@2x.d981e09a.png",
                ja = t.p + "Ribbon@3x.d6c8e50a.png",
                qa = t.p + "Spheres.c33c7b9a.png",
                Ya = t.p + "Spheres@2x.6b6732fa.png",
                $a = t.p + "Spheres@3x.5e58c98a.png",
                ae = t.p + "Star.2714eb9a.png",
                ee = t.p + "Star@2x.25a57fda.png",
                te = t.p + "Star@3x.206f9d8a.png",
                ie = t.p + "Success.ff2ef23a.png",
                ne = t.p + "Success@2x.97486aea.png",
                pe = t.p + "Success@3x.915e6dea.png",
                re = t.p + "ThumbsUp.0e3bffda.png",
                Ae = t.p + "ThumbsUp@2x.38e7642a.png",
                ge = t.p + "ThumbsUp@3x.ff9b6b0a.png",
                oe = t.p + "TrafficBarricade.067c8a9a.png",
                de = t.p + "TrafficBarricade@2x.9bde865a.png",
                he = t.p + "TrafficBarricade@3x.338b3bea.png",
                se = t.p + "TrafficBarricadeAlt.926ac6aa.png",
                le = t.p + "TrafficBarricadeAlt@2x.6cf6d65a.png",
                ce = t.p + "TrafficBarricadeAlt@3x.aaf995da.png",
                be = t.p + "TrafficLight.125db8da.png",
                fe = t.p + "TrafficLight@2x.c00a4f7a.png",
                xe = t.p + "TrafficLight@3x.c4bb5b8a.png",
                ue = t.p + "TrashCan.7ed1704a.png",
                we = t.p + "TrashCan@2x.79c8ba3a.png",
                Be = t.p + "TrashCan@3x.91184baa.png",
                Ce = {
                    ConfusedDog: { variants: [$, aa, ea], width: 465, height: 186 },
                    Success: { variants: [ie, ne, pe], width: 465, height: 186 },
                    Arrow: { variants: [g, o, d], width: 147, height: 100 },
                    Bench: { variants: [x, u, w], width: 311, height: 215 },
                    Blank: { variants: ["data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAATcAAADXAQAAAABXaiupAAAAAnRSTlMAAHaTzTgAAAAfSURBVHgB7cExAQAAAMIg+6c2xT5gJAAAAAAAAAAADiGYAAHjEk89AAAAAElFTkSuQmCC", "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAm4AAAGuAQAAAAAB07eXAAAAAnRSTlMAAHaTzTgAAAA4SURBVHgB7cEBDQAAAMIg+6c2xzdgIQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAGEsgABSmlaDAAAAABJRU5ErkJggg==", "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA6UAAAKFAQAAAAAcgXJpAAAAAnRSTlMAAHaTzTgAAABfSURBVHgB7cGBAAAAAMOg+1MfZNUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIO8pXQABmRxXNgAAAABJRU5ErkJggg=="], width: 311, height: 215 },
                    Cat: { variants: [v, T, S], width: 311, height: 215 },
                    Clipboard: { variants: [R, E, L], width: 233, height: 161 },
                    CoinsHand: { variants: [W, _, O], width: 233, height: 161 },
                    CoinsStairs: { variants: [I, N, Q], width: 311, height: 215 },
                    CoinsThumbs: { variants: [J, X, K], width: 311, height: 215 },
                    OneFinger: { variants: [ka, ya, Ra], width: 311, height: 215 },
                    PaperAirplane: { variants: [Ea, La, Ma], width: 311, height: 215 },
                    Puzzle: { variants: [_a, Oa, Ia], width: 311, height: 215 },
                    ThumbsUp: { variants: [re, Ae, ge], width: 311, height: 215 },
                    TrafficBarricade: { variants: [oe, de, he], width: 311, height: 215 },
                    TrafficBarricadeAlt: { variants: [se, le, ce], width: 311, height: 215 },
                    TrafficLight: { variants: [be, fe, xe], width: 147, height: 100 },
                    UTurn: { variants: [t.p + "UTurn.619b3aaa.png", t.p + "UTurn@2x.83237a8a.png", t.p + "UTurn@3x.67d2b35a.png"], width: 311, height: 215 },
                    DiscoGlobe: { variants: [ra, Aa, ga], width: 311, height: 215 },
                    Award: { variants: [h, s, l], width: 80, height: 96 },
                    Badge: { variants: [c, b, f], width: 48, height: 48 },
                    Crown: { variants: [pa], width: 88, height: 88 },
                    Bonus: { variants: [B, C, m], width: 48, height: 48 },
                    Gem: { variants: [sa, la, ca], width: 48, height: 48 },
                    Chat: { variants: [P, k, y], width: 36, height: 36 },
                    Cog: { variants: [M, z, U], width: 36, height: 36 },
                    Coin: { variants: [Z, F, G], width: 36, height: 36 },
                    CoinPurse: { variants: [H, V, D], width: 36, height: 36 },
                    Cone: { variants: [j, q, Y], width: 36, height: 36 },
                    Cross: { variants: [ta, ia, na], width: 36, height: 36 },
                    FirstAid: { variants: [oa, da, ha], width: 36, height: 36 },
                    Heart: { variants: [ba, fa, xa], width: 36, height: 36 },
                    LifeSaver: { variants: [ua, wa, Ba], width: 36, height: 36 },
                    Lightbulb: { variants: [Ca, ma, va], width: 36, height: 36 },
                    NoEntry: { variants: [Ta, Sa, Pa], width: 36, height: 36 },
                    Pencil: { variants: [za, Ua, Za], width: 36, height: 36 },
                    PiggyBank: { variants: [Fa, Ga, Ha], width: 36, height: 36 },
                    Plant: { variants: [Va, Da, Wa], width: 36, height: 36 },
                    PuzzlePieces: { variants: [Na, Qa, Ja], width: 36, height: 36 },
                    Ribbon: { variants: [Xa, Ka, ja], width: 36, height: 36 },
                    Spheres: { variants: [qa, Ya, $a], width: 36, height: 36 },
                    Star: { variants: [ae, ee, te], width: 36, height: 36 },
                    TrashCan: { variants: [ue, we, Be], width: 36, height: 36 },
                    Wallet: { variants: [t.p + "Wallet.0ca9943a.png", t.p + "Wallet@2x.d3b0554a.png", t.p + "Wallet@3x.90c942fa.png"], width: 36, height: 36 },
                },
                me = (a) => {
                    const { "aria-label": e = "", style: t, type: A, width: g = A.width } = a,
                        {
                            aspectRatio: o,
                            customVariants: d,
                            image: h,
                        } = ((a) => {
                            const { height: e, variants: t, width: i } = a;
                            return { aspectRatio: i / e, image: { url: t[0], width: i * (t.length + 1), height: e * (t.length + 1) }, customVariants: t.map((a, t) => ({ uri: a, width: i * (t + 1), height: e * (t + 1) })) };
                        })(A),
                        s = { width: g, height: Math.round(g / o) };
                    return i.createElement(n.Z, { style: [ve.illustration, t, s] }, i.createElement(p.Z, { "aria-label": e, aspectMode: r.Z.exact(o), customVariants: d, draggable: !1, image: h }));
                },
                ve = A.default.create((a) => ({ illustration: { alignSelf: "center" } }));
        },
    },
]);
//# sourceMappingURL=https://ton.local.twitter.com/responsive-web-internal/sourcemaps/client-web/shared~ondemand.SettingsRevamp~ondemand.SettingsMonetization~ondemand.SettingsSuperFollows~ondemand.SettingsA.b90abdca.js.map
